[package]
rust-version.workspace = true
name = "sdkwork-terminal-pty-runtime"
version.workspace = true
edition.workspace = true

[lints]
workspace = true
[lib]
path = "src/lib.rs"

[dependencies]
portable-pty = "0.9"
serde.workspace = true
sdkwork-terminal-shell-integration.workspace = true
sdkwork-utils-rust.workspace = true
